spring:
  application:
    name: cas
  profiles:
    # active: dev
    active: prod
  jackson:
    date-format: yyyy/M/d HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis:
  basepackage: cn.lanyue.cas.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
mapper:
  safe-delete: true
  safe-update: true
#  style: camelhumpandlowercase
#  before: true
#   identity: SELECT REPLACE(UUID(),''-'','''') as id

wx:
  miniapp:
    configs:
    - appid: 我的appid
      secret: 我的secret
      token: 
      aesKey: #微信小程序消息服务器配置的EncodingAESKey
      msgDataFormat: JSON
      qrcodeUrl: pages/{scopeType}?estateId=

cas:
  contact-phone: 17323079376
  contact-name: 刘先生
  blockchain:
   

caffeine:
  configs:
  - name: SMS
    initialCapacity: 
    maximumSize: 
    expireAfterWriteDuration: 
